version: '3.2'

networks:
  cysdvps:
    driver: bridge

services:

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cysce.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd!
    networks:
      - cysdvps
    ports:
      - "8061:80"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passw0rd
    #entrypoint: ["sleep","3h"]
    command: ["start --import-realm"]
    networks:
      - cysdvps
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - keycloak-conf:/opt/keycloak/conf
      - keycloak-import:/opt/keycloak/data/import

volumes:
  keycloak-conf:
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: /home/ubuntu/keycloak_UCI/data/conf
  keycloak-import:
      driver: local
      driver_opts:
          type: 'none'
          o: 'bind'
          device: /home/ubuntu/keycloak_UCI/data/import

